org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

author=thetadev
modid=constructionwand

mcversion=1.16.1
forgeversion=32.0.108
mcp_mappings=20200723-1.16.1

# Source: https://maven.blamejared.com/vazkii/botania/Botania/
botania=1.16-398
# Source: https://dvs1.progwml6.com/files/maven/mezz/jei/
jei_version=jei-1.16.1:7.0.1.10

version_major=2
version_minor=5